#!/usr/bin/env Rscript

#Taking in arguments
library("optparse")
 
option_list = list(
  make_option(c("-a", "--annotated_file"), type="character", default=NULL, 
              help="annotated file generated by bedtools annotate", metavar="filetype"),
  make_option(c("-c", "--counts"), type="character", default=NULL, 
              help="counts file indicating file in 1st column and # of counts in 2nd column relevant to bed files used in annotation", metavar="filetype"),
  make_option(c("-s", "--singlestrand"), action = "store_true", default = FALSE, 
              help="to draw meme of the concensus",metavar="logical"),
  make_option(c("-g", "--genome"), type="character", default='~/p-fstorici3-0/rich_project_bio-storici/reference/hg38/filtered_hg38.fa.fai', 
              help="genome infor, chromosomes with sizes", metavar="filetype"),
  make_option(c("-f", "--fileorder"), type="character", default=NULL, 
              help="order in which user prefers to visualize results. 1stcol:order number; 2ndcol:Filename; 3rdcol:Libraryname 4thcol:Cellline/Samplename, 5thcol:Replicate info", metavar="filetype"),
  make_option(c("-t", "--subtype_col"), type="integer", default=6, 
              help="column in the annotated file which is to be used for subtypes [default %default] "),
  make_option(c("-o", "--output_prefix"), type="character", default="out", 
              help="output file name [default %default]", metavar="character")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

#Checking for required input
writeLines("\n...Checking input...\n")
if (is.null(opt$annotated_file)){
  print_help(opt_parser)
  stop("Please specify annotated file.n", call.=FALSE)
}

if (is.null(opt$counts)){
  print_help(opt_parser)
  stop("Please specify counts file.n", call.=FALSE)
}

if (is.null(opt$fileorder)){
  print_help(opt_parser)
  stop("Please specify file order.n", call.=FALSE)
}

if (is.null(opt$genome)){
  print_help(opt_parser)
  stop("Please specify file order.n", call.=FALSE)
}

if (is.null(opt$subtype_col)){
  print_help(opt_parser)
  stop("Please specify file order.n", call.=FALSE)
}


#####Main Script
#1.Calling required Packages
writeLines("\n...Calling required Package(s)...\n")

library(ggthemes)
library(lemon)
library(pheatmap)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggpubr)
library(matrixStats)
library(rstatix)


#library(rstatix)
#library(annotatr)


#2.Defining functions if any
writeLines("\n...Defining required functions...\n")

#3. Preprocessing input files
writeLines("\n...Processing Input files...\n")

#annotated file
anno<-as.data.frame(read.table(opt$annotated_file, sep="\t", header = F, quote=""))
ncol=length(anno)
#annotation order
counts=as.data.frame(read.table(opt$counts, sep=" ", fill = TRUE,header = F,stringsAsFactors=FALSE, quote=""))
annotation_order=counts[["V1"]]
genome<-as.data.frame(read.table(opt$genome , sep="\t",header = F, quote=""))
Totalribos=counts[["V2"]]
#Totalribos<-colSums(anno[,(ncol-length(annotation_order)+1):ncol])

#reorder
order=as.data.frame(read.table(opt$fileorder, sep="\t",header = F, quote=""))
colnames(order)[1:5]=c("num", "Filename","Library","Cellline", "Rep")
order=order[order(order$num),]
lab=paste(order$Library,order$Cellline,order$Rep,sep="-")


#4.Main code
writeLines("\n...Executing Main code...\n")

########################################

dfstart=(ncol-length(annotation_order)+1)
colnames(anno)[1:6]<-c("chr","start","stop","id","length","strand")
colnames(anno)[opt$subtype_col]<-'Subtype'
colnames(anno)[dfstart:ncol]<-annotation_order
length= anno[,3]-anno[,2]

rpb=anno
rpb[dfstart:ncol]<-sweep(anno[,dfstart:ncol], 1, unlist(length), "/")
ppb=rpb
ppb[dfstart:ncol]<-sweep(rpb[,dfstart:ncol], 2, Totalribos, "/")
rm(rpb)
if (opt$singlestrand) {
  writeLines("\n...Calculating EF for single strand...\n")
  ppb[dfstart:ncol]=ppb[dfstart:ncol]*2
}
enrich=ppb

#### Calculating rNMPs per 100kbp per million rNMPs in genome
ppb=cbind(ppb[,c(1:(ncol-length(annotation_order)))],ppb[,paste(order$Filename)])
ppb = na.omit(ppb)
colnames(ppb)[dfstart:ncol(ppb)]<-c(lab)
ppb[dfstart:ncol(ppb)] = ppb[dfstart:ncol(ppb)]*10^5*10^6 #rNMPs per 100kb per million rNMPs in genome for both strands
subtypes=aggregate(x= ppb[,c(c(dfstart:ncol(ppb)))], by = list(ppb$Subtype), FUN="mean")
write.table(subtypes, paste(opt$output_prefix,"_subtype_freq_avg.tsv",sep=""),sep="\t", row.names=F, col.names=T, quote=F)

rm(ppb)

enrich[dfstart:ncol]=enrich[dfstart:ncol]*sum(genome[2])
enrich = na.omit(enrich)

enrich=cbind(enrich[,c(1:(ncol-length(annotation_order)))],enrich[,paste(order$Filename)])
colnames(enrich)[dfstart:ncol(enrich)]<-c(lab)
write.table(enrich, paste(opt$output_prefix,"_regions_EF.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)

#enrich[dfstart:ncol]= lapply(enrich[dfstart:ncol],as.numeric)
colnames(enrich)[opt$subtype_col] ='Subtype'
enrich_average<-enrich[,c(1:(ncol-length(annotation_order)))]
enrich_median<-enrich[,c(1:(ncol-length(annotation_order)))]
for (i in unique(order$Cellline)) {
  # TPW: pattern matching updated to be more explicit (exact cell-line column selection)
  cell_labs <- lab[order$Cellline == i]
  enrich_average[,i]<-rowMeans(dplyr::select(enrich, all_of(cell_labs)))
  enrich_median[,i]<-rowMedians(as.matrix(dplyr::select(enrich, all_of(cell_labs))))
}

write.table(enrich_average, paste(opt$output_prefix,"_regions_EF_avg.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)
write.table(enrich_median, paste(opt$output_prefix,"_regions_EF_median.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)

#df for subtypes
#df=anno[,c(1:6,opt$subtype_col, (ncol-length(annotation_order)+1):ncol)]
df=enrich[,c(1:6,opt$subtype_col, dfstart:ncol(enrich))]
colnames(df)[7]<-'Subtype'
#Enrichment per subtype
dfcol=ncol(df)
df$length=df$stop-df$start
subtypes=aggregate(x= df[,c(5,8:dfcol)], by = list(df$Subtype), FUN="mean")
write.table(subtypes, paste(opt$output_prefix,"_subtype_EF_avg.tsv",sep=""),sep="\t", row.names=F, col.names=T, quote=F)

#subtypes[,c(-1,-2)]<-sweep(subtypes[,c(-1,-2)], 2, Totalribos, "/")*100
#subtypes[,2]<-(subtypes[,2])/sum(genome$V2)*100
#if (opt$singlestrand) {
#  writeLines("\n...Calculating subtype EF for single strand...\n")
#  subtypes[,c(-1,-2)]<-subtypes[,c(-1,-2)]*2
#}
#subtypes[,paste(order$Filename)]= lapply(subtypes[,paste(order$Filename)],as.numeric)

#subtypes=cbind(subtypes[,c("Group.1","length")],subtypes[,paste(order$Filename)])
#colnames(subtypes)=c("Group.1","length", lab)
#write.table(subtypes, paste(opt$output_prefix,"_subtype_percent.tsv",sep=""),sep="\t", row.names=F, col.names=T, quote=F)
#subtypes[,c(-1,-2)]<-sweep(subtypes[,c(-1,-2)], 1, unlist(subtypes$length), "/")
#write.table(subtypes, paste(opt$output_prefix,"_subtype_percent_normalized.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)
#rm(subtypes)
#5.Plotting
#mat=as.matrix(subtypes[,c(-1,-2)])
#ymax=round(max(mat))#*0.6
#png(paste(opt$output_prefix,"subtype.png", sep="_"), width =(2+(ncol(subtypes)*0.4)), height = (4+(nrow(subtypes)*0.4)), unit ='in', res=1000)

#pheatmap(mat, cluster_rows = F,cluster_cols = F, display_numbers = T, 
         #breaks = c(seq(0,1,length.out = 101)[-101], seq(1,ymax,length.out = 101)),
         #fontsize_number=12, number_color = "black",
         #fontsize_row = 12, fontsize_col = 12,
         #color=colorRampPalette(rev(brewer.pal(n=6, name = "RdBu")))(200),
         #labels_row=subtypes$Group.1,
         #labels_col=colnames(subtypes[,c(-1,-2)]))

#dev.off()

########################################
#library(combinat)

#df=enrich_average[,c(opt$subtype_col,(ncol-length(annotation_order)+1):ncol(enrich_average))]
#df$Subtype=factor(df$Subtype, levels=c("hg38_cpg_islands","hg38_cpg_shores","hg38_cpg_shelves","hg38_cpg_inter"))
#mat=gather(df, Cellline, Enrich,-Subtype)

#my_comparisons<-combn(colnames(df[-1]), 2)

#jpeg(paste("Cellline_distribution_outliers.jpeg", sep="_"), width =13, height = 10, unit ='in', res=600)
#r=ggboxplot(mat, x="Cellline", y="Enrich",, alpha = 0.2, ggtheme = theme_bw(base_size = 16), fill = "Cellline")+
  #facet_grid(Subtype ~.)+
  #geom_hline(yintercept = 1, linetype = 2)+
  #scale_y_continuous(limits = c(0, 8), breaks = seq(0,8,1))+
  #scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  #ylab("Average Enrichment")+
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) #axis.title=element_text(size=20,face="bold")
#r # +  stat_compare_means( method = "t.test", comparisons=my_comparisons)
#stat_compare_means(mapping=aes(label=as_label(..p.adj..)), comparisons=my_comparisons,label.y = c(5.5,6.25,7.0), method = "t.test", group.by = "Subtype")
#dev.off()


#jpeg(paste("Cellline_distribution.jpeg", sep="_"), width =13, height = 10, unit ='in', res=600)
#r=ggboxplot(mat, x="Cellline", y="Enrich",, alpha = 0.2, ggtheme = theme_bw(base_size = 16), fill = "Cellline", outlier.shape = NA,error.plot= "crossbar")+
  #facet_grid(Subtype ~.)+
  #geom_hline(yintercept = 1, linetype = 2)+
  #scale_y_continuous(limits = c(0, 8), breaks = seq(0,8,1))+
  #scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  #ylab("Average Enrichment")+
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) #axis.title=element_text(size=20,face="bold")
#r # +  stat_compare_means( method = "t.test", comparisons=my_comparisons)
#stat_compare_means(mapping=aes(label=as_label(..p.adj..)), comparisons=my_comparisons,label.y = c(5.5,6.25,7.0), method = "t.test", group.by = "Subtype")
#dev.off()

#stat=compare_means(Enrich ~ Cellline, data=mat,method = "t.test",group.by = "Subtype")

writeLines("\nJob Finished.\n")
writeLines(paste("Output file name:", paste(opt$output_prefix,'.png\n', sep="")))
