#!/usr/bin/env Rscript

#Taking in arguments
library("optparse")

option_list = list(
  make_option(c("-a", "--annotated_file"), type="character", default=NULL,
              help="annotated file generated by bedtools annotate", metavar="filetype"),
  make_option(c("-t", "--totalannot_file"), type="character", default=NULL,
              help="annotated file generated by bedtools annotate", metavar="filetype"),
  make_option(c("-c", "--counts"), type="character", default=NULL,
              help="counts file indicating file in 1st column and # of counts in 2nd column relevant to bed files used in annotation", metavar="filetype"),
  make_option(c("-b", "--background_perc"), type="integer", default=16,
              help="column in the annotated file which is to be used as background percentage for normalization [default %default] "),
  make_option(c("-f", "--fileorder"), type="character", default=NULL,
              help="order in which user prefers to visualize results. 1stcol:order number; 2ndcol:Filename; 3rdcol:Libraryname 4thcol:Cellline/Samplename, 5thcol:Replicate info", metavar="filetype"),
  make_option(c("-o", "--output_prefix"), type="character", default="out",
              help="output file name [default %default]", metavar="character")
);

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

#Checking for required input
writeLines("\n...Checking input...\n")
if (is.null(opt$annotated_file)){
  print_help(opt_parser)
  stop("Please specify annotated file.n", call.=FALSE)
}

if (is.null(opt$counts)){
  print_help(opt_parser)
  stop("Please specify counts file.n", call.=FALSE)
}

if (is.null(opt$fileorder)){
  print_help(opt_parser)
  stop("Please specify file order.n", call.=FALSE)
}


#####Main Script
#1.Calling required Packages
writeLines("\n...Calling required Package(s)...\n")

library(ggthemes)
library(lemon)
library(pheatmap)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggpubr)
library(matrixStats)
library(rstatix)


#library(rstatix)
#library(annotatr)


#2.Defining functions if any
writeLines("\n...Defining required functions...\n")

#3. Preprocessing input files
writeLines("\n...Processing Input files...\n")

#annotated file
anno<-as.data.frame(read.table(opt$annotated_file, sep="\t", header = F, quote=""))
total_anno<-as.data.frame(read.table(opt$totalannot_file, sep="\t", header = F, quote=""))

ncol=length(anno)
#annotation order
counts=as.data.frame(read.table(opt$counts, sep=" ", fill = TRUE,header = F,stringsAsFactors=FALSE, quote=""))
annotation_order=counts[["V1"]]
annotation_order=gsub("_nucl","", annotation_order)

#reorder
order=as.data.frame(read.table(opt$fileorder, sep="\t",header = F, quote=""))
colnames(order)[1:5]=c("num", "Filename","Library","Cellline", "Rep")
order=order[order(order$num),]

dfstart=(ncol-length(annotation_order)+1)
colnames(anno)[1:6]<-c("chr","start","stop","id","length","strand")
colnames(anno)[dfstart:ncol]<-annotation_order

colnames(total_anno)[1:6]<-c("chr","start","stop","id","length","strand")
colnames(total_anno)[dfstart:ncol]<-annotation_order

#4.Main code
writeLines("\n...Executing Main code...\n")

anno_sum<-anno[,c(1:(ncol-length(annotation_order)))]
for (i in unique(order$Cellline)) {
  anno_sum[,i]<-rowSums(anno[order[order$Cellline==i,'Filename']])
}
write.table(anno_sum, paste(opt$output_prefix,"_regions_counts_sum.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)

anno_average<-anno[,c(1:(ncol-length(annotation_order)))]

for (x in annotation_order) {
  anno[x]=anno[x]/total_anno[x]*100
}

for (i in unique(order$Cellline)) {
  anno_average[,i]<-rowMeans(anno[order[order$Cellline==i,'Filename']], na.rm=TRUE)
}

write.table(anno_average, paste(opt$output_prefix,"_regions_perc_avg.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)

anno_norm_perc<-anno[,c(1:(ncol-length(annotation_order)))]

# Fix: background column (pct_at/pct_gc) is a proportion (0-1), but anno rNMP values
# at this point are percentages (0-100). Multiply background by 100 before dividing
# so units match: rNMP_perc / (background_proportion * 50) = EF near 1 at background rate.
for (i in unique(order$Cellline)) {
  anno_norm_perc[,i]<-rowMeans(anno[order[order$Cellline==i,'Filename']], na.rm=TRUE)/(anno[,opt$background_perc]*50)
}

write.table(anno_norm_perc, paste(opt$output_prefix,"_regions_norm_perc.tsv", sep=""),sep="\t", row.names=F, col.names=T, quote=F)

#5.Plotting
